### ISSUE TITLE
A few API proposals

### ISSUE THREAD

**Issue by vadim-ex** [seomoz/bloomfilter-py#12]
There were a few development from August, and I would like to propose a few improvements that I can implement (quickly implement). I understand that it would inevitably cause followup refactoring in Moz code, so I would let it to your judgement. My reasoning is driven by (now) open-source nature of the repo.

1. `add_by_hash`:

    * With addition of the previous state (as returned value) to `add_by_hash` the name becomes somewhat misguiding. I would propose to change it to `update_by_hash`.

    * It is especially true if we would accept previous proposal. I would propose to make `update_by_hash` to return true/false in sync with `test_by_hash`.

    * (premature optimization?) Should we implement `add_by_hash` that returns no result? It would be a bit faster if the status is not needed, and would make `update_by_hash` more easy to understand (as optimized conjunction of two operations). The code would be duplicated, of course, but the duplication would be minimal (for example, basically no test-code duplication).

2. I dislike name `Rotating`. It is well understood in Moz, and probably has historical motivation, but in open world it seems sub-par. Can we rename it to `RotatingBloomFilter`, please? Again, I appreciate the time it would require refactoring of client code.

@b4hand @dlecocq @tammybailey @lindseyreno

**Comment by dlecocq** [comment]
No objections to (2) whatsoever. It's a pretty minimal change for clients.

For (1), I don't have very strong feelings either way. Does `add_by_hash` return a value as it stands now? If not, then I'm fine with a `update_by_hash` or `upcheck_by_hash` or the like.

**Comment by b4hand** [comment]
I think we've discussed this in person and electronically sufficiently. No particular objections were made to any of the proposals.
